env: dev
server: 0.0.0.0:9877
domain: http://119.45.133.29:9876
event:
  events:
    - event_engine_start
    - event_engine_stop
    - event_logger_ready
    - event_local_cron_ready
    - event_local_cron_done
    - event_distribute_cron_ready
    - event_distribute_cron_done
    - event_gin_server_up
log:
  writer_kinds:
    - dated_file
    - std_out

cron:
  local_tasks: []
  distribute_tasks:
    -
      name: cron_master
      uri: redis://default:Jiayou20260117redis@119.45.133.29:9877/0
      server_options:
        concurrency: 100